# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_card.ipynb.

# %% auto 0
__all__ = ['Card']

# %% ../nbs/00_card.ipynb 9
class Card:
    "Playing card"
    def __init__(self,
                 suit,     #An index into `suits`
                 rank):    #An index into `ranks`
            self.suit,self.rank= suit,rank
    def __str__(self): return f"{ranks[self.rank]}{suits[self.suit]}"
    __repr__ = __str__
